### ISSUE TITLE
Add support for theme settings

### ISSUE THREAD

**Issue by rubengees** [Blue-Reaper/Proxer-Essentials#26]
Personally, I don't like the primary color of the theme, but like the other improved visuals. I would like to have a setting for that! This could be in the form of a select with some predefined colors and/or an input for setting that.

Of course other aspects could be made customizable, too e.g. the global background color.

**Comment by Blue-Reaper** [comment]
Hey @constantincuy,
in the first step I tried to unite the hilight color (red) in one variable but I saw you used several different types of red (#e53749, #ef394a, #e43748, ...), is that on purpose, or can we simplify it to one color?

Variables in CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

**Comment by Blue-Reaper** [comment]
possible soultion:

1. use css variables for color
2. create variabels and :root pseudo-class with JS
3. make it possible for user to choose color as hex in variable (save in userscript-manager)
4. ? give user colorpicker
5. ? predefine sets of fitting hilight/background colors

**Comment by Blue-Reaper** [comment]
Hey @rubengees,
thank you very much for this great idea.

It's now possible to select your own colors.
Currently only in the beta, but I think it won't take long till the main version.
![grafik](https://user-images.githubusercontent.com/46467587/51793548-45cdd480-21c2-11e9-9057-4eab8a30ea7d.png)

I would be happy if you could give a feedback on the solution.

blue

**Comment by rubengees** [comment]
Hi @Blue-Reaper,

just tried it, works (and looks) perfect, thanks!

**Comment by rubengees** [comment]
One thing - just saw that the set accent color is not applied on the scrollbar.
That seems to use a static value of `rgba(243, 56, 74, 0.93)`.

**Comment by Blue-Reaper** [comment]
@rubengees  you are right, probably did't see it because it's not in hex.
It is already fixed in the beta, mayby you need to install the script again, I did't update the beta version number.

**Comment by rubengees** [comment]
Works!
