### ISSUE TITLE
Components that are not styled

### ISSUE THREAD

**Issue by constantincuy** [Blue-Reaper/Proxer-Essentials#36]
#  Components that are not styled
- [ ] Emoji selector
- [ ] "Wochenplan" header area
- [ ] Finish Forum styling

If you find any unstyled areas please report them here! :)

**Comment by Blue-Reaper** [comment]
- [ ] anime calender not just the header:
![grafik](https://user-images.githubusercontent.com/46467587/51790989-ce397e80-219c-11e9-800b-815c847ce96c.png)

**Comment by rubengees** [comment]
"Impressum" -> "Übersicht" -> "Seiteninhaber" looks weird (Not posting a screenshot for privacy reasons).
