### ISSUE TITLE
custom icons look pixelated on high resolution screens

### ISSUE THREAD

**Issue by rubengees** [Blue-Reaper/Proxer-Essentials#44]
On my 4k display the notification icons look a bit pixelated. Can we find better ones?

![](https://user-images.githubusercontent.com/8021265/51793706-11a7e300-21c5-11e9-9334-4840d33f99e2.PNG)

**Comment by rubengees** [comment]
Same for the stars in the context of reviews:

![](https://user-images.githubusercontent.com/8021265/51793867-d65ae380-21c7-11e9-821c-3ed886c581c7.PNG)

There are probably more, looking through all custom icons might be a good idea.

**Comment by Blue-Reaper** [comment]
@constantincuy  the new loading screen looks at 1080p a little pixelated too.

**Comment by Blue-Reaper** [comment]
replaced the following images with FontAwesome:
![grafik](https://user-images.githubusercontent.com/46467587/56083125-410fd880-5e21-11e9-91c7-0c3d6b9f4984.png)
![grafik](https://user-images.githubusercontent.com/46467587/56083141-56850280-5e21-11e9-8a2b-9308fec7f637.png)
![grafik](https://user-images.githubusercontent.com/46467587/56083149-761c2b00-5e21-11e9-973a-7a14d8d008db.png)

**Comment by Blue-Reaper** [comment]
More changes:
![grafik](https://user-images.githubusercontent.com/46467587/56395395-b40eba00-623a-11e9-90ea-bebb4180de2d.png)

Navigation bar
before:
```
#nav {
    background: url("https://logosart.de/proxer2-0/shade.png");
    height: 80px;
    border-bottom: 0px;
}
```
now:
```
#nav {
    background: linear-gradient(to bottom, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0));;
    border-bottom: 0px;
}
```
