### ISSUE TITLE
Notification popups have unused space

### ISSUE THREAD

**Issue by rubengees** [Blue-Reaper/Proxer-Essentials#46]
- OS: Arch Linux
- Browser: Chrome
- Version: Latest
- Userscript-Manager: Tampermonkey
- Display resolution: 3840x2160

The popup windows shown when clicking on one of the notification icons have too much space on the right size. Also, they seem to be a bit too long horizontally in general:

![](https://user-images.githubusercontent.com/8021265/51793842-6ba9a800-21c7-11e9-8e74-7d753610912f.PNG)

**Comment by Blue-Reaper** [comment]
Also on Firefox/Chrome with FullHD:
![grafik](https://user-images.githubusercontent.com/46467587/51793939-df988000-21c8-11e9-93b6-ff3aff8a643c.png)
